name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cuando hay un push en la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22  # O la versión que necesites

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: withastro/action@v0
        with:
          dist: dist  # Directorio de salida que Astro utiliza por defecto
